[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/sovol/printer_data/comms/klippy.sock
max_upload_size: 1024

[file_manager]
enable_object_processing: True

[job_queue]
load_on_startup: False

[history]

[data_store]
temperature_store_size: 600
gcode_store_size: 1000

[authorization]
force_logins: False
trusted_clients:
    127.0.0.1
    10.0.0.0/16
cors_domains:
    http://*.local
    https://*.local
    *:7136
    http://*/pgcode
    *
default_source: moonraker

[octoprint_compat]
stream_url: /webcam/?action=stream
webcam_enabled: True

# -================================-
#   Moonraker Update Manager
# -================================-
[update_manager]
enable_auto_refresh: True
refresh_interval: 72 # Hours
enable_system_updates: True
enable_packagekit: False
channel: dev

[include plugins/update_manager.conf]


[include plugins/configurations.conf]

[include plugins/cameras.conf]
#[include moonraker-obico-update.cfg]
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main